//executors
export const FETCH_EXECUTORS_REQUEST = 'FETCH_EXECUTORS_REQUEST';
export const FETCH_EXECUTORS_SUCCESS = 'FETCH_EXECUTORS_SUCCESS';
export const FETCH_EXECUTORS_FAILURE = 'FETCH_EXECUTORS_FAILURE';

export const FETCH_REFERENCES_REQUEST = 'FETCH_REFERENCES_REQUEST';
export const FETCH_REFERENCES_SUCCESS = 'FETCH_REFERENCES_SUCCESS';
export const FETCH_REFERENCES_FAILURE = 'FETCH_REFERENCES_FAILURE';

export const FETCH_REFERENCESTYPE_REQUEST = 'FETCH_REFERENCESTYPE_REQUEST';
export const FETCH_REFERENCESTYPE_SUCCESS = 'FETCH_REFERENCESTYPE_SUCCESS';
export const FETCH_REFERENCESTYPE_FAILURE = 'FETCH_REFERENCESTYPE_FAILURE';

export const FETCH_BYPASS_SHEET_REQUEST = 'FETCH_BYPASS_SHEET_REQUEST';
export const FETCH_BYPASS_SHEET_SUCCESS = 'FETCH_BYPASS_SHEET_SUCCESS';
export const FETCH_BYPASS_SHEET_FAILURE = 'FETCH_BYPASS_SHEET_FAILURE';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
